### PR TITLE
Bump Thanos v0.32.2

### PR DESCRIPTION
**Pull request by simonpasquier**
Manual sync because the revert from v0.31.0 to v0.30.2 (#112) fails the bot.

### CODE REVIEW

**Comment by simonpasquier** [comment]
/hold
until the 4.14 release branch is cut.

**Comment by simonpasquier** [comment]
/hold cancel

This can merge when the dev branch reopens.

**Comment by raptorsun** [comment]
shall we retitle the PR to v0.32.2? 👀

**Pull request merged**
