### PR TITLE
openshift: Add script to generate rh-manifest.txt

### PR DESCRIPTION
**Pull request by bison**
Until all repositories are integrated with Cachito, components shipped
as part of OpenShift that have non-golang dependencies must include an
`rh-manifest.txt` file listing these and their versions.  This adds a
script to generate this file.

See: https://issues.redhat.com/browse/MON-1173

### CODE REVIEW

**Comment by PhilipGough** [comment]
@bison this looks good to me. I was going to suggest we could add a make target for generation and add a test to prow but since it seems like this is an interim fix, perhaps it is not worth the time investment?

**Comment by bison** [comment]
Thanks, @PhilipGough. Yeah, that was my thought. I avoided the make target just to avoid annoying merge conflicts in the future. I do think a test in prow would be nice, but I'm not sure it's worth it now if this is going away soon.

**Review by PhilipGough — APPROVED** [review]
/lgtm

**Comment by paulfantom** [comment]
> I'm not sure it's worth it now if this is going away soon.

In my experience things that are supposed to go away soon, do not go away soon :package: 

Integrating this check into prow should be fairly easy even without make target. Just add following code after https://github.com/openshift/release/blob/master/ci-operator/config/openshift/thanos/openshift-thanos-master.yaml#L39:
```
- as: rh-manifests
  commands: ./scripts/rh-manifest.sh && git diff --exit-code
  container:
    from: src
```
and run `make jobs` as described in https://docs.ci.openshift.org/docs/how-tos/onboarding-a-new-component/#generating-prow-jobs-from-ci-operator-configuration-files

**Comment by PhilipGough** [comment]
/hold
based on @paulfantom suggestion to integrate prow

**Comment by bison** [comment]
Okay, we can do that. I guess we're supposed to add this to every release branch, so we'll need to do it in several places. Also, we can't do it until these are already merged, right? Do you want me to prep the PR for the prow config before approving this?

**Comment by paulfantom** [comment]
/hold cancel

To integrate it into prow, we need this PR merged first :)

> Do you want me to prep the PR for the prow config before approving this?

No, let's merge it first and add prow config in the meantime. It would be good to add that config in one PR too.

**Pull request merged**
