### PR TITLE
scripts: enable go modules in vendor verification script

### PR DESCRIPTION
**Pull request by paulfantom**
Enable go modules in vendor verification script

Also this should be a first PR after enabling Prow CI support, so after merging we should have an image available in CI registry.

/cc @s-urbaniak

### CODE REVIEW

**Comment by s-urbaniak** [comment]
@paulfantom this seems to be broken still :thinking:

**Comment by paulfantom** [comment]
I am trying to fix it in https://github.com/openshift/release/pull/4463

**Pull request merged**
