### PR TITLE
Synchronize with upstream

### PR DESCRIPTION
**Pull request by paulfantom**
Synchronize with upstream.

Closes #5

/cc: @LiliC @metalmatze @s-urbaniak

### CODE REVIEW

**Comment by LiliC** [comment]
/lgtm

Not sure I can approve, lets see :D

**Comment by metalmatze** [comment]
lgtm and apparently you can approve @LiliC :smile:

**Comment by s-urbaniak** [comment]
@LiliC if you can't approve, we consider it a bug :+1:

**Comment by paulfantom** [comment]
Just don't create BZ entry for it :trollface:

**Pull request merged**
