### PR TITLE
Bump v0.10.0

### PR DESCRIPTION
**Pull request by simonpasquier**

### CODE REVIEW

**Comment by simonpasquier** [comment]
/assign @bwplotka @squat 

I presume there's nothing blocking us from updating the Thanos components to v0.10.0

**Comment by s-urbaniak** [comment]
let's leave this on hold until https://github.com/thanos-io/thanos/pull/2015 is resolved.

**Comment by simonpasquier** [comment]
After discussing offline with @s-urbaniak it appears that we don't really the bump for now since v0.10.0 doesn't bring all what we need for multi-tenancy alerting.

**Pull request closed without merging**
