### PR TITLE
OCPBUGS-3764: Fix local-test for go 1.18

### PR DESCRIPTION
**Pull request by raptorsun**
This is a cherry pick of the commit https://github.com/thanos-io/thanos/commit/d704b7c8ded692e367be0a22d453932abf8d9df2
from upstream to fix the bug when running local test with golang 1.18 ([this PR](https://github.com/openshift/thanos/pull/82)).

* [ ] I added CHANGELOG entry for this change.
* [x] Change is not relevant to the end user.

## Verification

Check the CI local test

### CODE REVIEW

**Comment by jan--f** [comment]
/remove-lifecycle stale
/lgtm
@raptorsun Mind creating a bug report for this so we can get it merged?

**Comment by raptorsun** [comment]
> /remove-lifecycle stale /lgtm @raptorsun Mind creating a bug report for this so we can get it merged?

no problem, the bug report will be ready this afternoon :)

**Pull request merged**
