### PR TITLE
Bug 1945500: Bump downstream thanos to v0.20.2

### PR DESCRIPTION
**Pull request by arajkumar**
* [ ] I added CHANGELOG entry for this change.
* [x] Change is not relevant to the end user.

### CODE REVIEW

**Comment by dgrisonnet** [comment]
Holding as the version of nodejs used by the `react-app-test` job needs to be updated to >=12.0.0: https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_thanos/58/pull-ci-openshift-thanos-master-react-app-test/1399669373802647552

The version can be updated here: https://github.com/openshift/release/blob/master/ci-operator/config/openshift/thanos/openshift-thanos-master.yaml#L65, do you want to do the change @arajkumar?

You will also need to update the go vendor and push the changes.

/hold

**Comment by arajkumar** [comment]
@dgrisonnet, Thanks for looking into the failure. I want to try that.

**Comment by simonpasquier** [comment]
/lgtm
/hold
Can you prepare a WIP pull request to bump the version in the CMO repository? this way the bugzilla won't go to MODIFIED until both pull requests are merged.
Also feel free to add yourself to the OWNERS file and remove @s-urbaniak (I hope he won't mind :smile:)

**Comment by arajkumar** [comment]
> Also feel free to add yourself to the OWNERS file and remove @s-urbaniak (I hope he won't mind 😄)

@simonpasquier Thank you, I will do it in a separate PR. Hope that is fine :)

**Pull request merged**
