### PR TITLE
MON-1116: Bump to f55d854c

### PR DESCRIPTION
**Pull request by s-urbaniak**
This now also pulls in deduplication logic for Rules API

/cc @openshift/openshift-team-monitoring

### CODE REVIEW

**Comment by lilic** [comment]
think it needs a revendor? Otherwise yay!! 🎉

**Comment by simonpasquier** [comment]
You need to update the `vendor` directory :)

**Comment by s-urbaniak** [comment]
@lilic @simonpasquier indeed, i forgot about that one, ptal :+1:

**Comment by s-urbaniak** [comment]
/retest
so far everything unrelated

**Pull request merged**
