### PR TITLE
Bug 1870287: pkg/query: eventually update rules client

### PR DESCRIPTION
**Pull request by s-urbaniak**
This is a backport of https://github.com/thanos-io/thanos/pull/3280.

/cc @openshift/openshift-team-monitoring

### CODE REVIEW

**Review by lilic — COMMENTED** [review]
~Could we not bump to at least latest thanos release plus this patch? As this is master and 4.7 release, fine with backporting just this patch in 4.6 for example. WDYT?~

Nevermind I thought it was release but was only rc not full release.

/lgtm
/hold

**Comment by s-urbaniak** [comment]
@lilic yes, same thoughts :-) sorry for not expressing them in the PR title.

side note: also launching a cluster-bot cluster for a one-shot verification.

**Comment by s-urbaniak** [comment]
initial verification point: right after installation i get alerts:
image

**Comment by lilic** [comment]
sgtm, seems like there is a bug in thanos so new release won't happen for some time, feel free to remove hold when ready.

**Comment by s-urbaniak** [comment]
@lilic is it ok for you to unhold once green? I'll take it to bump Thanos once released.

**Pull request merged**
