### PR TITLE
MON-1302: Bump Thanos to v0.17.2

### PR DESCRIPTION
**Pull request by dgrisonnet**
Update Thanos downstream fork to the latest upstream release for the OpenShift 4.7 feature freeze checklist.

In addition to the bump, I also updated the OWNERS file.

### CODE REVIEW

**Comment by lilic** [comment]
There is a newer release than this, I guess you just missed it when opening this PR https://github.com/thanos-io/thanos/releases/tag/v0.17.2

**Comment by dgrisonnet** [comment]
Indeed, I missed it, thank you! :+1:

**Review by lilic — COMMENTED** [review]
/lgtm

**Comment by simonpasquier** [comment]
(nit) I think we can take `pkg/store/labelpb/label.go` from upstream

**Comment by dgrisonnet** [comment]
@simonpasquier good catch, thanks! It seems that my editor took some initiatives there :man_shrugging:. 

/unhold

**Pull request merged**
