### PR TITLE
OCPBUGS-2037: Bump 4.10 to 0.23.2

### PR DESCRIPTION
**Pull request by JoaoBraveCoding**
* [ ] I added CHANGELOG entry for this change.
* [ ] Change is not relevant to the end user.

### CODE REVIEW

**Comment by JoaoBraveCoding** [comment]
cc @jan--f @simonpasquier

**Comment by jan--f** [comment]
/lgtm
For future readers of this PR:
We're specifically after the fix in https://github.com/openshift/thanos/pull/92/commits/7b79fc7b0ab07d4d6a55ae0a4a9816ef91c752f8.

**Comment by juzhao** [comment]
tested with PR, thanos version is 0.23.2 and tabs under Observe from console all behave normal, no issues
/label cherry-pick-approved

**Pull request merged**
