### PR TITLE
OCPBUGS-21135: Bump golang.org/x/net to v0.17.0

### PR DESCRIPTION
**Pull request by danielmellado**

### CODE REVIEW

**Comment by simonpasquier** [comment]
IIUC you need to modify .gitignore to remove the `data/` entry which prevents the `vendor/golang.org/x/net/publicsuffix/data/` directory to be added:

https://github.com/openshift/thanos/blob/9f2b5ff512b8c396f7b4d006d7eafb5c7ca97fba/.gitignore#L16

**Review by raptorsun — APPROVED** [review]

**Pull request merged**
