### PR TITLE
Bug 1961158: Changing resolver to address thanos-ruler pod issues

### PR DESCRIPTION
**Pull request by prashbnair**
* [ ] I added CHANGELOG entry for this change.
* [ ] Change is not relevant to the end user.

### CODE REVIEW

**Review by kakkoyun — COMMENTED** [review]
Rather than modifying the downstream fork's default value, why can't we just change the value of the flag?

**Comment by prashbnair** [comment]
@simonpasquier Can you please let @kakkoyun know why it was done this way in 4.7

**Comment by simonpasquier** [comment]
> Rather than modifying the downstream fork's default value, why can't we just change the value of the flag?

Because the prometheus operator doesn't allow you to set the flag in a simple fashion: the resolver flag being hidden, we can't reasonably expose it in the Thanos ruler CRD and [merge patch](https://github.com/prometheus-operator/prometheus-operator/blob/master/Documentation/user-guides/strategic-merge-patch.md) doesn't work because the container's `args` field is an array and the merge operation would replace the array generated by the operator.
I've raised the question in https://github.com/thanos-io/thanos/issues/4204, happy to hear your feedback :)

In the short term, patching the downstream fork is unfortunately our only viable option since this issue blocks our ability to merge anything on the `release-4.6` branch in CMO.

/lgtm

**Comment by juzhao** [comment]
tested with the not merged PR, issue is fixed
/label qe-approved

**Pull request merged**
