### PR TITLE
MON-3725: Update OWNERS: move raptorsun out of reviewer

### PR DESCRIPTION
**Pull request by raptorsun**
* [ ] I added CHANGELOG entry for this change.
* [x] Change is not relevant to the end user.

### CODE REVIEW

**Review by slashpai — APPROVED** [review]
/lgtm

**Comment by danielmellado** [comment]
let's hold onto this one until the window is open again, I don't think we should open a jira just for that ;)

**Comment by danielmellado** [comment]
@raptorsun mind editing your PR and add the reference to https://issues.redhat.com/browse/MON-3725 ? Thanks!

**Comment by raptorsun** [comment]
done @danielmellado  :)

**Pull request merged**
